### ISSUE TITLE
Support variable reference for css

### ISSUE THREAD

**Issue by yarastqt** [yarastqt/themekit#62]
## Proposal

Add var reference for css files (optionally)

### Config

```json
{
  "format": "css/variables",
  "options": {
    "keepVars": true
  }
}
```

### Tokens

```yml
color:
  controls:
    type:
      action:
        fillColor:
          base:
            value: "#fff"

button:
  fillColor:
    value: "{color.controls.type.action.fillColor.base.value}"
```

#### Result

```css
:root {
    --color-controls-type-action-fill-color-base: #fff;
    --button-fill-color: var(--color-controls-type-action-fill-color-base);
}
```
