### ISSUE TITLE
Impl command or flag for fix invalid tokens

### ISSUE THREAD

**Issue by yarastqt** [yarastqt/themekit#93]
## Proposal

Implement command or flag for fix invalid tokens, and remove duplicate tokens.

### Broken path

We have override tokens with broken path:

**base**

```yml
color:
  base:
    value: "#fff"
```

**override**

```yml
color-base:
    value: "#fff"
```

In result we have warning for different tokens with same result.

### Duplicate tokens

**base**

```yml
color:
  base:
    value: "#fff"
```

**override**

```yml
color:
  base:
    value: "#fff"
```

### Command

```sh
themekit build --fix
```
